apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: enterprise-ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
  namespace: monitoring
  annotations:
    backup.kubernetes.io/enabled: "true"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: enterprise-ssd
  resources:
    requests:
      storage: 100Gi