apiVersion: v1
kind: Secret
metadata:
  name: istio-gateway-cert
  namespace: istio-system
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t # placeholder cert
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t # placeholder key