# Secret will be automatically created by cert-manager Certificate resource
# Self-signed certificate for development
# For production, use proper CA-signed certificates
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-gateway-cert
  namespace: istio-system
spec:
  secretName: istio-tls-cert
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - "*.${var.domain_name}"
  - "${var.domain_name}"