apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiod
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istiod
  template:
    metadata:
      labels:
        app: istiod
    spec:
      containers:
      - name: discovery
        image: docker.io/istio/pilot:1.19.0
        securityContext:
          runAsNonRoot: true
          runAsUser: 1337
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 15010