name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Basic validation
      run: |
        echo "✅ Repository structure validation"
        ls -la
        
    - name: Check required files
      run: |
        echo "📋 Checking required files..."
        test -f README.md && echo "✅ README.md exists"
        test -f LICENSE && echo "✅ LICENSE exists"
        test -f Makefile && echo "✅ Makefile exists"
        echo "✅ All required files present"