name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Basic validation
      run: |
        echo "✅ Repository structure validation"
        ls -la
        
    - name: Check required files
      run: |
        set -e
        echo "📋 Checking required files..."
        for file in README.md LICENSE Makefile; do
          test -f "$file" && echo "✅ $file exists"
        done
        echo "✅ All required files present"