name: Infrastructure Security Scan

on:
  schedule:
    - cron: '0 5 * * 4'  # Weekly on Thursday at 5 AM
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'k8s/**'

jobs:
  infrastructure-scan:
    name: Infrastructure Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Terraform security scan
      uses: bridgecrewio/checkov-action@master
      with:
        directory: terraform/
        framework: terraform
        soft_fail: true
        
    - name: Kubernetes security scan
      uses: bridgecrewio/checkov-action@master
      with:
        directory: k8s/
        framework: kubernetes
        soft_fail: true
        
    - name: Terraform static analysis
      run: |
        echo "🔍 Running Terraform static analysis"
        find terraform/ -name "*.tf" | head -10 || echo "No Terraform files found"
        
    - name: Kubernetes policy validation
      run: |
        echo "📋 Validating Kubernetes security policies"
        find k8s/ -name "*policy*" -o -name "*security*" | head -5 || echo "No policy files found"