name: Terraform Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-validate.yml'

jobs:
  terraform-validate:
    name: Terraform Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
        
    - name: Terraform Format Check
      run: terraform fmt -check -recursive terraform/
      
    - name: Terraform Init
      run: |
        cd terraform/environments/dev
        terraform init -backend=false
        
    - name: Terraform Validate
      run: |
        cd terraform/environments/dev
        terraform validate
        
    - name: TFLint
      uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: v0.44.1
        
    - name: Run TFLint
      run: |
        tflint --init
        tflint terraform/ --recursive